from . import main
from . import auth
from . import uploads
from . import scores
from . import players
from . import api
from . import games
from . import create
from . import delete
from . import startup
